<?php
require './src/templates/layout.phtml';   

?>

<h1>Ecran d'admin</h1>

<nav class="admin_menu">
    <div class="nav_element">
        <a href="/ProjetFinal/projet_freaky-kawaii-molds/admin/manageProduct"> <!--link Manage Products (Create, Update, Delete)-->
            <div class="">
            </div>
            <p>Gestion des produits</p>
        </a>
    </div>
    
    <div class="nav_element">
        <a href="/ProjetFinal/projet_freaky-kawaii-molds/admin/manageCategories"> <!--link Manage Categories (Create, Update, Delete)-->
            <div class="">
            </div>
            <p>Gestion des catégories</p>
        </a>
    </div>
       
    <div class="nav_element">
        <a href="/ProjetFinal/projet_freaky-kawaii-molds/admin/manageUser"><!--link Manage User ( Search and Delete)-->
        <div class="">
            </div>
            <p>Gestion des utilisateurs</p>
        </a>
    </div>
    <div class="nav_element">
        <a href="/ProjetFinal/projet_freaky-kawaii-molds/admin/showOrders"><!--link Manage Orders (Search and Read)-->
        <div class="">
        </div>
        <p>Gestion des commandes</p>
    </a>
        </div>

</nav>