<?php
require './src/templates/adminPanel.phtml'; 
?>

<table>

    <thead>
        <tr>
            <th>Pseudonyme</th>
            <th>email</th>
            <th>Suppression</th>
        </tr>
    </thead>
    <tbody>
<?php
$userManager = new UserManager();
$userArray= $userManager->getAllNonAdminUsers();

for($i=0,$max=count($userArray);$i<$max;$i++){
?>
        <tr>
            <td><?=$userArray[$i]['username']?></td>
            <td><?=$userArray[$i]['email']?></td>
            <td>
                <form action="/ProjetFinal/projet_freaky-kawaii-molds/admin/manageUser" method="post">
                <input type="hidden" name="userId" value=<?=$userArray[$i]['id']?>>
                <button type="submit" class="deletebtn">Supprimer l'utilisateur</button>
                </form>
            </td>
        </tr>

<?php
}
?>
    </tbody>
</table>