<?php
require './src/templates/adminPanel.phtml'; 
?>

<table>

    <thead>
        <tr>
            <th>Numéro de commande</th>
            <th>Total</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
<?php

for($i=0,$max=count($orders);$i<$max;$i++){
// formatting the date before displaying it
$date=date("d/m/Y",strtotime($orders[$i]['order_date']));
?>
        
        <tr>
            
                
                <td><a href="<?='/ProjetFinal/projet_freaky-kawaii-molds/orderHistory/details/'.$orders[$i]['id']?>"> Commande numéro <?=$orders[$i]['id']?></a></td>
                <td><?=$orders[$i]['total_price']?>  €</td>
                <td><?=$date?></td>
          
        </tr>
   

<?php
}
?>
    </tbody>
</table>