<?php
require './src/templates/adminPanel.phtml'; 
?>

<h1>NOUVEAU PRODUIT</h1>

<?php
// If errors were detected during the submit
if (!empty($errors))
{
?>
<section class=form-errors>
  <ul>
    <?php
    foreach ($errors as $key=>$error)
    {
    ?>
      <li><?=$error?></li>
    <?php  
    }
    ?>
  </ul>
</section>
<?php
}
?>

<!-- Update the product -->
<form action="/ProjetFinal/projet_freaky-kawaii-molds/admin/createProduct" method="post" enctype="multipart/form-data">
Image principale du produit:
<input type="file" multiple name="fileToUpload" id="fileToUpload">

<br><!-- BR A ENLEVER -->
<label>Veuillez entrer le Nom du produit</label>
<input type="text" value="" name="newLabel">

<br><!-- BR A ENLEVER -->
<label for="category-select">Veuillez entrer une description du produit</label>
<input type="text" value="" name="newDescription">

<br><!-- BR A ENLEVER -->
<label>Veuillez choisir une catégorie</label>
<select name="newCategoryId" id="category-select">
<?php
for($i=0,$max=count($categoriesArray);$i<$max;$i++)
{
    ?>
    <option value="<?=$categoriesArray[$i]['id']?>">
    <?=$categoriesArray[$i]['label']?>
    </option>
<?php
};
?>
</select>

<!--<br><!-- BR A ENLEVER -->
<!--<label>Versions du produit</label>-->
<!--<ul id="variantsList">-->
 
<!--</ul>-->
<!--    <label>Nouvelle version</label>-->
<!--    <input type="text" value="" id="newVariantLabel">-->
<!--    <label>Prix</label>-->
<!--    <input type="number" step="0.01" value="" id="newVariantPrice">-->
<!--    <button id="addVariant">Ajouter cette variante</button>-->

<!--<br> <!-- A supprimer -->
<a class="button" href="https://ericlefranc.sites.3wa.io/ProjetFinal/projet_freaky-kawaii-molds/admin/manageProduct">Annuler</a>
<button type="submit">Enregistrer les modifications</button>   
</form>