<?php

?>
<header>
    <?php
    //If a user is online, we display his username. Else we display the links to the signIn and signUp forms
            if(isset($_SESSION['user']))
            {
                echo $_SESSION['user']['username'];
                echo "<br>";
    ?>
            <!-- Change profile -->
            <a  href='/ProjetFinal/projet_freaky-kawaii-molds/editUser'>Modifier son profil</a>    
 
            
            <!-- Log out -->
            <a class="logOut" href="/ProjetFinal/projet_freaky-kawaii-molds/homescreen">
                <form action="/ProjetFinal/projet_freaky-kawaii-molds/logout" method="post">
                <button type="submit" class="btnLink">Déconnexion</button>    
                </form>
                <p>Se déconnecter</p>
            </a>
    <?php
                if(($_SESSION['user']['is_admin'] == 1 ))
                {
    ?>            
                
                <!-- Admin Pannel -->
                <a class='admin-panel' href='/ProjetFinal/projet_freaky-kawaii-molds/admin'>Panel admin</a>    
                
    <?php
                }
            
    ?>
                <!-- A EFFACER UNE FOIS LE LOGOUT TERMINE -->
                <div class="logs">
                    <a class="signIn" href="/ProjetFinal/projet_freaky-kawaii-molds/signIn">
                        <p>Se connecter</p>
                    </a>
                </div>
                <div>
                    <a class="signUp" href="/ProjetFinal/projet_freaky-kawaii-molds/signUp">
                        <p>S'inscrire</p>
                    </a>
                </div
    <?php    
                
            }
            else
            {
    ?>
            <div class="logs">
                    <a class="signIn" href="/ProjetFinal/projet_freaky-kawaii-molds/signIn">
                        <p>Se connecter</p>
                    </a>
                <div>
                    <a class="signUp" href="/ProjetFinal/projet_freaky-kawaii-molds/signUp">
                        <p>S'inscrire</p>
                    </a>
                </div>
                <div>
                    <a class="log-out" href="#"><i class="fa-solid fa-arrow-right-from-bracket"></i></a>
                </div>
                <div class="logo">
                    <a href="/ProjetFinal/projet_freaky-kawaii-molds/index.php">
            
                    </a>
                </div>
                </div>                
                
    <?php
            }
    ?>
    
</header>