<?php
session_start();
?>
<header>
    <div class="logs">
        <a class="signIn" href="signIn">
            <p>Se connecter</p>
        </a>
        <a class="signUp" href="signUp">
            <p>S'inscrire</p>
        </a>
        <a class="log-out" href="#"><i class="fa-solid fa-arrow-right-from-bracket"></i></a>
    </div>
    <div class="logo">
        <a href="index.php">

        </a>
    </div>
    </div>
</header>