<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>FREAKY KAWAII MOLDS</title>
    <link rel="stylesheet" href="../css/style.css" type="text/css" />
    <script src="https://kit.fontawesome.com/c72217183e.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cuprum&display=swap" rel="stylesheet">
</head>

<body>
<?php

//We don't display the header and navbar when we are on the signIn or signUp form
if(!(isset($_GET['path']) && 
(  $_GET['path']==='signIn' 
|| $_GET['path']==='signUp')))
{
require './src/templates/header.phtml';
require './src/templates/NavigationHeader.phtml';
}
?>
