<nav class="nav_header">
    <div class="nav_element">
        <a href="index.php?route=homescreen"> <!--link Accueil-->
            <div class="">
            </div>
            <p>Accueil</p>
        </a>
    </div>
       
    <div class="nav_element">
        <a href="index.php?route=newProducts"><!--link Nouveautés-->
        <div class="">
            </div>
            <p>Nouveautés</p>
        </a>
    </div>
    <div class="nav_element">
        <a href="index.php?route=bestSales"><!--link Meilleurs ventes-->
        <div class="">
        </div>
        <p>Meilleures ventes</p>
    </a>
        </div>
        <div class="nav_element">
            <a href="index.php?route=discounts"><!--link Articles en Promo-->
            <div class="">
            </div>
            <p>Promotions</p>
        </a>
        </div>
</nav>