<nav class="nav_header">
    <div class="nav_element">
        <a href="/ProjetFinal/projet_freaky-kawaii-molds/"> <!--link Accueil-->
            <div class="">
            </div>
            <p>Accueil</p>
        </a>
    </div>
       
    <div class="nav_element">
        <a href="/ProjetFinal/projet_freaky-kawaii-molds/"><!--link Nouveautés-->
        <div class="">
            </div>
            <p>Nouveautés</p>
        </a>
    </div>
    <div class="nav_element">
        <a href="/ProjetFinal/projet_freaky-kawaii-molds/"><!--link Meilleurs ventes-->
        <div class="">
        </div>
        <p>Meilleures ventes</p>
    </a>
        </div>
        <div class="nav_element">
            <a href="/ProjetFinal/projet_freaky-kawaii-molds/"><!--link Articles en Promo-->
            <div class="">
            </div>
            <p>Promotions</p>
        </a>
        </div>
</nav>