<?php
require './src/templates/layout.phtml';   

?>

<form action="/ProjetFinal/projet_freaky-kawaii-molds/signIn" method="post">
  <div class="container">
    <h1>Se connecter</h1>
    <p>Veuillez remplir ce formulaire afin de vous connecter.</p>
    <hr>
    
    <div>
    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Email" name="email" required>
    </div>
    
    <div>
    <label for="password"><b>Mot de passe</b></label>
    <input type="password" placeholder="Mot de passe" name="password" required>
    </div>
  
    <div>
    <label for="password-repeat"><b>Confirmation Mot de passe</b></label>
    <input type="password" placeholder="Confirmation Mot de passe" name="password-repeat" required>
    </div>
    
    <p>En créant votre compte Freaky Kawaii Molds, vous acceptez nos <a href="#" style="color:dodgerblue">Conditions d'utilisation</a> 
    et notre <a href="#" style="color:dodgerblue">Politique de confidentialité</a>.</p>

    <div class="clearfix">
      <!-- bouton CANCEL à refaire -->
      <a href="index.php"><button type="button" class="cancelbtn">Cancel</button></a>
      <button type="submit" class="signupbtn">Sign Up</button>
    </div>
  </div>
</form>