    <table>
    
        <thead>
            <tr>
                <th>Nom</th>
                <th>Catégorie</th>
            </tr>
        </thead>
        <tbody>
    <?php
    for($i=0,$max=count($prodCat);$i<$max;$i++){
    ?>
            <tr>
                <td><a href='/ProjetFinal/projet_freaky-kawaii-molds/admin/manageProduct/<?=$prodCat[$i]['product_id']?>'><?=$prodCat[$i]['product_label']?></a></td>
                <td><?=$prodCat[$i]['category_label']?></td>
            </tr>
    
    <?php
    }
    ?>
        </tbody>
    </table>